export const Skills = [
  {
    cat: [
      ["ARMY_JOB", 0],
      ["DEFENSE", 10],
    ],
    desc: "$ gains one life point for every level-up",
    desc2:
      "If you're not looking for responsibility, just hoping to survive, this is the job for you!",
    eid: null,
    id: ["ADRENALINE", 43],
    min: 0,
    name: "Soldier",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 50,
  },
  {
    cat: [
      ["ARMY_JOB", 0],
      ["SUPPORT", 19],
    ],
    desc: "Heals a teammate 5 life points +1 additional LP per level-up. Immune to poison and paralysis.",
    desc2:
      "The toughest part of being a doctor is learning to tell the difference between the living and the dead. That saves a load of time!",
    eid: null,
    id: ["AK47", 20],
    min: 0,
    name: "Doctor",
    num: 3,
    open: [
      ["DUAL_PISTOLS__", 12],
      ["SPITEFUL", 116],
      ["KING_OF_BOULES__", 108],
      ["DOUBLE_BARREL_SHOTGUN__", 15],
    ],
    rec: 50,
    swe: 2,
    type: ["SUPER", 4],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["ARMY_JOB", 0],
      ["VEHICULE", 22],
    ],
    desc: "Increases the chances of getting a vehicle by 25% every level-up",
    desc2:
      "Yeah, because with your current level, a machine would do a better job than you, grunt!",
    eid: null,
    id: ["AMPHETAMINE_SHOT__", 44],
    min: 0,
    name: "Pilot",
    num: null,
    open: [["SURVIVOR_INSTINCT", 124]],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["ARMY_JOB", 0],
      ["MUNITION", 20],
      ["SUPPORT", 19],
    ],
    desc: "Reloads munitions for a teammate when reinforcements arrive. One per level-up. Doubles the frequency of use of grenades.",
    desc2:
      "\"The human bomb, you've got that job wrapped up! There's even a place in your heart for the detonator! \"",
    eid: null,
    id: ["ANATOMY", 45],
    min: 0,
    name: "Munitions",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["ARMY_JOB", 0],
      ["DEPLOY", 8],
      ["SPEED", 7],
    ],
    desc: "+1 deployment bonus (20 maximum)",
    desc2: "Knowledge of the terrain is the key to victory!",
    eid: null,
    id: ["ARTIFICER", 3],
    min: 0,
    name: "Scout",
    num: 2,
    open: [
      ["SPARROW_HAWK", 35],
      ["FRENZY", 79],
    ],
    rec: 50,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["ARMY_JOB", 0],
      ["DEPLOY", 8],
      ["SAP", 9],
    ],
    desc: "$ appears in the enemy camp. +50 initiative points (+10 more for each level-up)",
    desc2:
      "The art of infiltrating the enemy camp and causing carnage before the battle has even begun...",
    eid: null,
    id: ["ASSAULT_RIFLE__", 18],
    min: 0,
    name: "Spy",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["ARMY_JOB", 0],
      ["DEPLOY", 8],
      ["TEAM", 15],
    ],
    desc: "+1 en communication for each level-up",
    desc2:
      "Comms officers ensure the correct transmission of battle orders. Having plenty of Comms agents guarantees you'll receive plenty of enjoyable orders, allowing you to massacre even more enemies!",
    eid: null,
    id: ["BACK_PACK", 46],
    min: 0,
    name: "Comms. Officier",
    num: null,
    open: [["TUCK_AND_ROLL__", 128]],
    rec: null,
    swe: null,
    type: ["POOL", 5],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["ARMY_JOB", 0],
      ["SAP", 9],
      ["TEAM", 15],
    ],
    desc: "+1 en sabotage for each level-up",
    desc2:
      "It's even easier when the guys you're facing are armed with nothing but water pistols and harsh language",
    eid: null,
    id: ["BAIT", 47],
    min: 0,
    name: "Saboteur",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["POOL", 5],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["HANDGUN", 4],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BARREL_EXTENSION", 48],
    min: 0,
    name: "Pistol",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["HANDGUN", 4],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BAZOOKA_M1", 24],
    min: 0,
    name: "Revolver",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["HANDGUN", 4],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BAZOOKA_M25", 26],
    min: 0,
    name: "Desert Eagle",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["HANDGUN", 4],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BERETTA", 11],
    min: 0,
    name: "Beretta",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BIG_CALVES", 49],
    min: 0,
    name: "Dual pistols",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BINOCULARS", 50],
    min: 0,
    name: "Shotgun",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BIPOD", 51],
    min: 0,
    name: "Semi-auto Shotgun",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BLIND_FURY__", 52],
    min: 0,
    name: "Double-barrelled Shotgun",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["ON_POINT__", 53],
    min: 0,
    name: "Pump Action Shotgun",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["WIFE_BEATER__", 54],
    min: 0,
    name: "Scattergun",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["BULL", 55],
    min: 0,
    name: "Assault Rifle",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["EXPLOSIVE_SHELLS__", 56],
    min: 0,
    name: "M16",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["HYDROSHCOK_SHELLS__", 57],
    min: 0,
    name: "AK47",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["PARALYZING_SHELLS__", 58],
    min: 0,
    name: "FAMAS",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN1", 2],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["ARMOR_PIERCING_SHELLS__", 59],
    min: 0,
    name: "Thompson",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["TOXIC_SHELLS__", 60],
    min: 0,
    name: "UMP",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["CAMOUFLAGE", 61],
    min: 0,
    name: "Bazooka M1",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["LOADER__", 62],
    min: 0,
    name: "Rocket Launcher",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["CHARGE", 63],
    min: 0,
    name: "Bazooka M25",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["CK_MAGELLAN", 36],
    min: 0,
    name: "Infernal Tube",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["CLEVER", 64],
    min: 0,
    name: "Comanche Auto",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["CLOUT", 65],
    min: 0,
    name: "Heavy Machine Gun",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["COFFEE_THERMOS", 66],
    min: 0,
    name: "Gatling Gun",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["COLD_BLOOD", 67],
    min: 0,
    name: "Minigun",
    num: null,
    open: [["SCOUT", 4]],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["COMANCHE_AUTO", 28],
    min: 0,
    name: "Sniper",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["SCAVENGER__", 68],
    min: 0,
    name: "MOS-TECK",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["COMMAND", 69],
    min: 0,
    name: "Lizaro Jungle",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["COMMANDO", 70],
    min: 0,
    name: "Sparrowhawk",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["COMPENSATOR", 71],
    min: 0,
    name: "CK-Magellan",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN2", 3],
      ["OFFENSE", 5],
    ],
    desc: null,
    desc2: null,
    eid: null,
    id: ["COM_OFFICER", 6],
    min: 0,
    name: "Knife",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["WEAPON", 2],
    vh: null,
    weight: 10,
  },
  {
    cat: [["VEHICULE", 22]],
    desc: "The light tank comes equipped with a light cannon and a machine gun",
    desc2:
      '"A balsa wood structure mounted on a bicycle... It still freaks the enemy right out though! "',
    eid: null,
    id: ["COVER", 72],
    min: 4,
    name: "Light tank",
    num: null,
    open: [],
    rec: null,
    swe: 16,
    type: ["SPAWN", 6],
    vh: null,
    weight: 20,
  },
  {
    cat: [["VEHICULE", 22]],
    desc: "The motorbike takes you to within range of the first target",
    desc2:
      '"Does it not scare you to always be first to charge the enemy? <br/>- Oh no, what really hacks me off is the number of flies I swallow en route."',
    eid: null,
    id: ["COVER_FIRE", 73],
    min: 0,
    name: "Motorcycle",
    num: null,
    open: [],
    rec: null,
    swe: 3,
    type: ["SPAWN", 6],
    vh: null,
    weight: 30,
  },
  {
    cat: [["VEHICULE", 22]],
    desc: "The jet bombards the battlefield until it runs out of fuel",
    desc2: '"This is Ghostrider One requesting a fly-by."',
    eid: null,
    id: ["INVICIBLE__", 74],
    min: 8,
    name: "Fighter Jet",
    num: null,
    open: [],
    rec: null,
    swe: 12,
    type: ["SPAWN", 6],
    vh: null,
    weight: 10,
  },
  {
    cat: [["VEHICULE", 22]],
    desc: "The helicopter is equipped with a double machine gun",
    desc2: '"I feel much stronger, check out my rotor! "',
    eid: null,
    id: ["DESERT_EAGLE", 10],
    min: 4,
    name: "Helicopter",
    num: null,
    open: [],
    rec: null,
    swe: 12,
    type: ["SPAWN", 6],
    vh: null,
    weight: 5,
  },
  {
    cat: [["VEHICULE", 22]],
    desc: "The heavy tank comes equipped with a cannon and a machine gun",
    desc2:
      '"Formidable on the battlefield, but the aircon is an optional extra. "',
    eid: null,
    id: ["DISTRUSTFUL", 75],
    min: 4,
    name: "Heavy Tank",
    num: null,
    open: [],
    rec: null,
    swe: 24,
    type: ["SPAWN", 6],
    vh: null,
    weight: 1,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "Every shot that misses $ makes him act quicker",
    desc2:
      '"How do I motivate my troops?... \nHehe, everyone has their little secrets! "',
    eid: null,
    id: ["DODGE", 76],
    min: 0,
    name: "Adrenaline",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["EQUIPMENT", 11],
    ],
    desc: "+100% speed bonus for 500 turns",
    desc2: '"I was a bicycle courier previously. I\'m used to it..."',
    eid: 0,
    id: ["DOUBLE_BARREL_SHOTGUN__", 15],
    min: 0,
    name: "Amphetamine Shot",
    num: 1,
    open: [],
    rec: 20,
    swe: 4,
    type: ["SUPER", 4],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["SCIENCE", 26],
    ],
    desc: "Doubles the chance of inflicting a fatal shot. Increases the chances of $ hitting their favourite body part",
    desc2:
      '"Yes! \nMy 27<text:span text:style-name="T1">th</text:span> toe in 24hours!"',
    eid: null,
    id: ["DUAL_PISTOLS__", 12],
    min: 0,
    name: "Anatomy",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["EQUIPMENT", 11],
      ["DEPLOY", 8],
    ],
    desc: "After moving once, all $'s munitions are recharged",
    desc2: '"Hey, enjoy!"',
    eid: 2,
    id: ["ENTHUSIAST", 138],
    min: 5,
    name: "Rucksack",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["STRATEGY", 16],
    ],
    desc: "+8 life points, $ will be picked as the priority target, and will be easier to hit.",
    desc2: '"Hey, guys! Why am I the only one with a flashing neon uniform? "',
    eid: null,
    id: ["FAMAS__", 21],
    min: 0,
    name: "Bait",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["EQUIPMENT", 11],
    ],
    desc: "+1 range bonus +10% aim bonus for all weapons",
    desc2: "\"It's not what you do with it that counts. It's the size.\"",
    eid: 33,
    id: ["FIRST_AID", 77],
    min: 0,
    name: "Barrel Extension",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["FITNESS", 12],
    ],
    desc: "+3 life points and +25% move speed bonus",
    desc2: '"The army is no place for wet blankets!"',
    eid: null,
    id: ["OUT_OF_BOUNDS__", 78],
    min: 0,
    name: "Huge calves",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["DEPLOY", 8],
      ["EQUIPMENT", 11],
    ],
    desc: "The enemy deploys a new trooper with a 400 point initiative penalty.",
    desc2: '"Ewww, their commander picks his nose during the briefing."',
    eid: 32,
    id: ["FRENZY", 79],
    min: 0,
    name: "Binoculars",
    num: 2,
    open: [],
    rec: 50,
    swe: 1,
    type: ["SUPER", 4],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["EQUIPMENT", 11],
    ],
    desc: "No penalty for moving targets",
    desc2: '"Eye on the ball, head in the game. That\'s how I roll!"',
    eid: 28,
    id: ["FRIENDLY_FIRE", 80],
    min: 0,
    name: "Biped",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["UNKNOWN4", 13],
    ],
    desc: "$ will not incur any line of sight penalties, neither will he be penalised when firing blind",
    desc2: '"they hardly ever wash, I can aim for the smell."',
    eid: null,
    id: ["FULL_ARMOR", 81],
    min: 5,
    name: "Blind Fury",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["FITNESS", 12],
    ],
    desc: "$ takes their turn before the others (+200 en initiative)",
    desc2: '"Me! Me! I\'ll go first!"',
    eid: null,
    id: ["GATLING_GUN", 30],
    min: 0,
    name: "On Point",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["EQUIPMENT", 11],
    ],
    desc: "+30% speed bonus and +30% dodge bonus",
    desc2: '"I feel much more free in my vest."',
    eid: 24,
    id: ["GRENADE_BLACKHOLE__", 91],
    min: 5,
    name: "Wife Beater",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["TEAM", 15],
    ],
    desc: "+3 life points, and anyone behind $ will benefit from added cover",
    desc2: '"Scouts only report one guy... This\'ll be a walk in the park."',
    eid: null,
    id: ["FLASHBANG__", 83],
    min: 0,
    name: "Brick S***house",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["EQUIPMENT", 11],
    ],
    desc: "$ fires up to 6 explosive shells, doubling their damage",
    desc2: "My heart goes boom!",
    eid: 4,
    id: ["GRENADE_SHOCK__", 87],
    min: 0,
    name: "Explosive shells",
    num: 6,
    open: [],
    rec: 0,
    swe: 3,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["EQUIPMENT", 11],
    ],
    desc: "All bullets fired by $ are 4 times as likely to result in a killshot",
    desc2:
      "So basically it shatters into a million pieces which fly everywhere. Cool, huh?",
    eid: 3,
    id: ["GRENADE_GAS__", 84],
    min: 0,
    name: "Hydroshock shells",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SAP", 9],
      ["EQUIPMENT", 11],
    ],
    desc: "All bullets fired by $ paralyse the enemy",
    desc2:
      '"It\'s awesome, you shoot the guy and he goes stiff! <br/>- Yeah... So just like normal bullets then..."',
    eid: 1,
    id: ["GRENADE_HOLY__", 89],
    min: 0,
    name: "Paralysing shells",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["EQUIPMENT", 11],
    ],
    desc: "All bullets fired by $ will not be stopped by enemy armor",
    desc2: '"What bulletproof vest? "',
    eid: 34,
    id: ["GRENADE_HEALING__", 90],
    min: 6,
    name: "Armor-piercing shells",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SAP", 9],
      ["EQUIPMENT", 11],
    ],
    desc: "$ fires up to 3 toxic shells which poison the enemy",
    desc2:
      '"You look a little off-colour there Roger. Are you sure you don\'t need a little lie down? "',
    eid: 5,
    id: ["GRENADE_CLOWN__", 85],
    min: 0,
    name: "Toxic shells",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["STRATEGY", 16],
    ],
    desc: "20% of shots targeting $ will miss, and the chances of them being selected as a target are also reduced",
    desc2:
      '"Chief ! That box over there – it moved! <br/>- Of course it did Jack..."',
    eid: null,
    id: ["GRENADE_GLUE__", 88],
    min: 0,
    name: "Camouflage",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["EQUIPMENT", 11],
    ],
    desc: "The weapon selected by $ is automatically reloaded",
    desc2: '"My number one rule: always have a spare clip in your pants."',
    eid: 6,
    id: ["GRENADE_FRAGMENTATION__", 86],
    min: 0,
    name: "Loader",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["STRATEGY", 16],
    ],
    desc: "$ charges at a nearby enemy",
    desc2: '"Frrreeeeee Huuuuuggsss ! ! ! "',
    eid: null,
    id: ["GRENADE__", 82],
    min: 3,
    name: "Charge",
    num: 2,
    open: [],
    rec: 0,
    swe: 4,
    type: ["SUPER", 4],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["CHARACTER", 14],
    ],
    desc: "$ will have an additional choice when they level-up. Counters the effects of Bait, Pink Grenade and Propoganda. Reduces the chance of enemy sabotage by half.",
    desc2:
      '"None of that stuff bothers me. I consider all the options before I make my choices."',
    eid: null,
    id: ["HARD_BOILED", 92],
    min: 0,
    name: "Smart",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["FITNESS", 12],
    ],
    desc: "+1 damage for punches. When $ hits an enemy he has a 50% chance of dropping their weapon",
    desc2:
      '"Rocky, at least take this pistol... <br/>- No thanks chief, don\'t need it! "',
    eid: null,
    id: ["HEART_BREAKER", 93],
    min: 0,
    name: "Fists of Fury",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["EQUIPMENT", 11],
    ],
    desc: "+25% speed increase",
    desc2: '"I take my war without sugar. Victory is sweet enough."',
    eid: 7,
    id: ["HEAT_SENSOR__", 94],
    min: 0,
    name: "Thermos of coffee",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["CHARACTER", 14],
    ],
    desc: "$ takes aim twice as quickly",
    desc2: '"We\'re not going to waste time talking sense here..."',
    eid: null,
    id: ["HEAVYWEIGHT__", 95],
    min: 0,
    name: "Cold Blooded",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["EQUIPMENT", 11],
      ["SAP", 9],
    ],
    desc: "Recovers an enemy weapon",
    desc2: '"Haha check this out – I also got his fillings."',
    eid: 22,
    id: ["INFERNAL_TUBE__", 27],
    min: 2,
    name: "Scavenger",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["SUPER", 4],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEPLOY", 8],
      ["TEAM", 15],
    ],
    desc: "+1 battle per day ( +2 max )",
    desc2:
      '"My job is a leader of men. <br/>I tell them where to go. <br/>I don\'t go there though."',
    eid: null,
    id: ["HURRY", 96],
    min: 10,
    name: "Commander",
    num: 1,
    open: [],
    rec: 50,
    swe: 10,
    type: ["SUPER", 4],
    vh: true,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["FITNESS", 12],
    ],
    desc: "+5 life points",
    desc2:
      '"Look. If we remove the brain, that leaves more room for life points."',
    eid: null,
    id: ["HYPERACTIVE", 97],
    min: 0,
    name: "Commando",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["EQUIPMENT", 11],
    ],
    desc: "Halves the aiming penalty incurred when firing successive shots. Also reduces the waiting time after firing by 30%",
    desc2: '"Wave goodbye to the shakes with a Parkin & Sons compensator!"',
    eid: 35,
    id: ["INTERCEPTION", 98],
    min: 0,
    name: "Compensator",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [["DEFENSE", 10]],
    desc: "When $ is reloading, he has a 50% chance of avoiding being hit",
    desc2: '"We told you to keep your head down..."',
    eid: null,
    id: ["SEMELLES_DE_PLOMB__", 140],
    min: 0,
    name: "Take Cover!",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["STRATEGY", 16],
      ["TARGET", 21],
    ],
    desc: "Whan $ is in firing position, he returns fire immediately",
    desc2: '"Have we quite finished shooting at me?! "',
    eid: null,
    id: ["JUGGLER", 99],
    min: 5,
    name: "Covering Fire",
    num: 2,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: true,
    weight: 30,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["FITNESS", 12],
    ],
    desc: "$ cannot be killed by a normally fatal shot",
    desc2: '"Argh... My head! My he... Ah no, it\'s ok. As you were."',
    eid: null,
    id: ["LIZARO_JUNGLE", 34],
    min: 2,
    name: "Invincible",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["CHARACTER", 14],
    ],
    desc: "+200 initiative points per enemy spy present upon deployment.\nInvulnerable to sabotage. Cannot be hurt by his teammates.",
    desc2: '"Erm John, you didn\'t have a moustache this morning..."',
    eid: null,
    id: ["BULLETPROOF_VEST", 100],
    min: 5,
    name: "Suspicious",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["FITNESS", 12],
    ],
    desc: "The first shot fired at him is automatically dodged.",
    desc2: '"Ta daaa! Thank you for your kind applause! "',
    eid: null,
    id: ["KNIFE", 37],
    min: 0,
    name: "Dodger",
    num: 1,
    open: [],
    rec: 50,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["EQUIPMENT", 11],
    ],
    desc: "$ regains up to 50% of their life points at the end of the first round",
    desc2: '"Erm, I\'ve got a Band-Aid left if anyone needs it."',
    eid: 8,
    id: ["LASER_SIGHTS__", 101],
    min: 5,
    name: "First Aid",
    num: 2,
    open: [],
    rec: 100,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["DEPLOY", 8],
      ["STRATEGY", 16],
    ],
    desc: "If $ is not in a vehicle, he can appear outside the deployment zone",
    desc2:
      "\"Hahaha we've got them now – I'm going round the back to trap them.\"",
    eid: null,
    id: ["LAST_MOHICAN", 102],
    min: 5,
    name: "Out of Bounds",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "When $ defeats an enemy, he gains 200 initiative points",
    desc2: '"Neeeeeexxxxxt! "',
    eid: null,
    id: ["LUCKY_CHARM", 103],
    min: 0,
    name: "Frenetic",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["TEAM", 15],
      ["STRATEGY", 16],
      ["DEFENSE", 10],
    ],
    desc: "Grenades and shots fired by $ never hit teammates",
    desc2:
      '"Thanks to our revolutionary technology, it\'s now impossible to get shot in the ass! "',
    eid: null,
    id: ["M16", 19],
    min: 5,
    name: "Friendly Fire",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["EQUIPMENT", 11],
    ],
    desc: "Reduces damage sustained by 1 and reduces speed by 20%",
    desc2:
      "\"Haha! Who's in this tin can? <br/>- Oh knackers, it's the commander! <br/>- Ah... Oops.\"",
    eid: 9,
    id: ["MACHINE_GUN", 29],
    min: 0,
    name: "Heavy Armor",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 5,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "Explodes in a zone covering 2x2 and causing between 6 and 12 damage",
    desc2: '"Simple and effective: throw it, everything is clean."',
    eid: 10,
    id: ["TAIL_GUNNER__", 104],
    min: 0,
    name: "Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 8,
    type: ["SUPER", 4],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["SAP", 9],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "All troopers affected are blinded",
    desc2: '"Staring at the sun! "',
    eid: 11,
    id: ["MARTYR", 139],
    min: 0,
    name: "Flashbang",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 8,
    type: ["SUPER", 4],
    vh: null,
    weight: 15,
  },
  {
    cat: [
      ["SAP", 9],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "All troopers affected are poisoned",
    desc2: '"Extremely effective! Well... Unless the enemy has a cold."',
    eid: 12,
    id: ["MEDIC", 1],
    min: 0,
    name: "Gas Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 8,
    type: ["SUPER", 4],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "Makes a clown appear on an empty square",
    desc2: '"I\'m s-s-scared of clowns, chief... <br/>- Me too! FIRE! "',
    eid: 13,
    id: ["MINIGUN", 31],
    min: 2,
    name: "Clown Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 8,
    type: ["SUPER", 4],
    vh: null,
    weight: 3,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "Explodes into fragments, causing between 1 and 5 damage",
    desc2: '"Ow! Ah! Oww!... But! Aaaah! "',
    eid: 14,
    id: ["MOS_TECK", 33],
    min: 0,
    name: "Fragmentation Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 8,
    type: ["SUPER", 4],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SAP", 9],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "All troopers affected will drop their weapon",
    desc2: '"The best bit about it is that this really firms up the buttocks."',
    eid: 15,
    id: ["NERVOUS", 106],
    min: 2,
    name: "Shock Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 6,
    type: ["SUPER", 4],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SAP", 9],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "All troopers affected lose 200 initiative points",
    desc2:
      '"And how exactly do we get rid of this bloody glue? <br/>- You can\'t. No point in looking."',
    eid: 16,
    id: ["NIMBLE_FINGERS", 105],
    min: 0,
    name: "Glue Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 6,
    type: ["SUPER", 4],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "Explodes in a zone covering 3x3 and causing between 12 and 24 damage",
    desc2: '"I... I have seen the light, people... \n" BOOOM!',
    eid: 17,
    id: ["OCCUPATION", 107],
    min: 10,
    name: "Grenade bénie",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 18,
    type: ["SUPER", 4],
    vh: null,
    weight: 5,
  },
  {
    cat: [
      ["SUPPORT", 19],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "Heals troopers in a zone measuring 3x3",
    desc2: '"It stings a bit at the start, but it gets better."',
    eid: 18,
    id: ["KING_OF_BOULES__", 108],
    min: 0,
    name: "Healing Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 4,
    type: ["SUPER", 4],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["EQUIPMENT", 11],
      ["GRENADA", 17],
    ],
    desc: "Wipes out all enemies on a zone measuring 2x2.",
    desc2:
      '"Haha! Behold, our latest invention! Now, can we have a volunteer for the first test?... <br/>No? Nobody? "',
    eid: 19,
    id: ["PILOT", 2],
    min: 10,
    name: "Black Hole Grenade",
    num: 1,
    open: [["SNIPER", 32]],
    rec: 120,
    swe: 32,
    type: ["SUPER", 4],
    vh: null,
    weight: 2,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["CHARACTER", 14],
    ],
    desc: "$ incurs no further penalty when seriously injured",
    desc2: '"Pffft, doesn\'t even hurt. "',
    eid: null,
    id: ["PISTOL", 8],
    min: 0,
    name: "Hard Boiled",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["UNKNOWN4", 13],
    ],
    desc: "The chances of $ inflicting a fatal shot to the heart are multiplied by 3",
    desc2: '"Oh Carl... You\'re breaking my heart! Mom was right..."',
    eid: null,
    id: ["PUMP_SHOTGUN", 16],
    min: 0,
    name: "Heartbreaker",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["EQUIPMENT", 11],
    ],
    desc: "+20% aiming bonus. $'s bullets cannot be dodged",
    desc2:
      "\"- Here? <br/>- No way, it's cold out there... <br/>- And here? <br/>- You're getting warmer! <br/>- How about here? <br/>- Good job, you're real hot... \" <br/>BANG!",
    eid: 29,
    id: ["RADIO", 109],
    min: 0,
    name: "Heat sensor",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["FITNESS", 12],
    ],
    desc: "+10 life points -20% loss of speed",
    desc2: '"Quite simply, a beast."',
    eid: null,
    id: ["REVERSE_ATTACK__", 110],
    min: 2,
    name: "Heavyweight",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 5,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "+10% speed increase and doubles the frequency of use of powers and equipment",
    desc2: '"Get a move on guys, Rambo is on TV tonight!"',
    eid: null,
    id: ["RESCUER", 111],
    min: 5,
    name: "Hurry",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "+50% speed bonus and will run interference on the enemy",
    desc2:
      '"Battle won, chief! Your uniform has been ironed! The dishes have been washed! The battlefield re-seeded! "',
    eid: null,
    id: ["RESILIENCE", 112],
    min: 2,
    name: "Hyperactif",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 5,
  },
  {
    cat: [["DEFENSE", 10]],
    desc: "$ intercepts and throws back any grenades that land nearby",
    desc2: '"Right back at ya! "',
    eid: null,
    id: ["RESTLESS__", 113],
    min: 5,
    name: "Interception",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 10,
  },
  {
    cat: [["SPEED", 7]],
    desc: "$ can switch weapons instantly",
    desc2: '"Anything up to a bazooka, no worries. Tanks, however..."',
    eid: null,
    id: ["REVOLVER", 9],
    min: 0,
    name: "Juggler",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["EQUIPMENT", 11],
    ],
    desc: "+1 armor, and halves the chance of taking a fatal shot to the torso",
    desc2:
      '"More than 20 different colours! Sand, forest, spangly disco number..."',
    eid: 23,
    id: ["ROCKET_LAUNCHER", 25],
    min: 0,
    name: "Bulletproof vest",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["UNKNOWN4", 13],
      ["EQUIPMENT", 11],
    ],
    desc: "+80% improved aim",
    desc2: '"Battlefield show-off."',
    eid: 25,
    id: ["RUSH", 114],
    min: 0,
    name: "Laser Sights",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["UNKNOWN4", 13],
    ],
    desc: "When $ is the last man standing, he automatically empties his clip every time he fires and any damage caused is doubled",
    desc2:
      "\"Well, he's all alone now, maybe he'll stop being such a dramaaaaaaaargh...\"",
    eid: null,
    id: ["SABOTEUR", 7],
    min: 2,
    name: "Last Mohican",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 3,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["EQUIPMENT", 11],
    ],
    desc: "A fatal shot will still leave $ with one life point instead of dying",
    desc2:
      '"What a stroke of luck, the shrapnel got stuck in my rabbit\'s foot! "',
    eid: 20,
    id: ["SCATTERGUN__", 17],
    min: 0,
    name: "Lucky Charm",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["UNKNOWN4", 13],
    ],
    desc: "$ fires 2 extra times per burst from an automatic weapon",
    desc2: '"I love the sound of a Gatling in the morning."',
    eid: null,
    id: ["SCOUT", 4],
    min: 0,
    name: "Tail Gunner",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["FITNESS", 12],
    ],
    desc: "$ operates weapons twice as quickly and loads his weapon 2 shells at a time",
    desc2:
      '"That Jackson does my head in, showing off with his 60 phalanges..."',
    eid: null,
    id: ["EYE_OF_THE_TIGER__", 115],
    min: 0,
    name: "Nimble Fingers",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "$ occasionally empties the whole clip",
    desc2: '"Empty? Already? "',
    eid: null,
    id: ["SHOTGUN", 13],
    min: 2,
    name: "Nervous",
    num: 1,
    open: [],
    rec: 0,
    swe: 2,
    type: ["AUTO", 3],
    vh: null,
    weight: 5,
  },
  {
    cat: [
      ["DEPLOY", 8],
      ["STRATEGY", 16],
    ],
    desc: "$ earns 1 [T] every day of connection",
    desc2: '"I\'m here to stay! "',
    eid: null,
    id: ["SHOTGUN_AUTO", 14],
    min: 10,
    name: "Occupation",
    num: 3,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["UNKNOWN4", 13],
    ],
    desc: "Grenades thrown by $ never miss their target",
    desc2: '"Him over there, his head looks like a decent target."',
    eid: null,
    id: ["SNIPER", 32],
    min: 2,
    name: "King of Boules",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["EQUIPMENT", 11],
      ["STRATEGY", 16],
      ["DEPLOY", 8],
    ],
    desc: "+1 communication bonus",
    desc2:
      '"You\'re listening to Radio Troopers on 7.62, stay tuned to this frequency! "',
    eid: 26,
    id: ["SOLDAT", 0],
    min: 10,
    name: "Radio",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEPLOY", 8],
      ["STRATEGY", 16],
    ],
    desc: "The enemy deployment zone is reduced by 2 squares",
    desc2: '"What? Coffee time already? "',
    eid: null,
    id: ["SPARROW_HAWK", 35],
    min: 8,
    name: "Reverse Attack",
    num: 1,
    open: [],
    rec: 50,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SUPPORT", 19],
      ["DEPLOY", 8],
    ],
    desc: "$ takes a dead soldier to the reserves and heals them",
    desc2:
      '"I saw a tunnel, with a light at the end, and... <br/>- Yeah whatever, you\'ve been saved now. Get back in the game! "',
    eid: null,
    id: ["SPITEFUL", 116],
    min: 0,
    name: "Saviour",
    num: 1,
    open: [],
    rec: 100,
    swe: 2,
    type: ["SUPER", 4],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["FITNESS", 12],
    ],
    desc: "When $ is knocked to the ground, he takes no damage, gets up immediately and gains +100 initiative points",
    desc2:
      '"These are the new weapons-grade Y-fronts. <br/>With these, the war is already won."',
    eid: null,
    id: ["SPRINTER__", 117],
    min: 5,
    name: "Bounce Back",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [["DEPLOY", 8]],
    desc: "When an allied or enemy trooper moves, $ gains 200 initiative points",
    desc2: '"Brilliant, there are more of them! "',
    eid: null,
    id: ["SPY", 5],
    min: 5,
    name: "Restless",
    num: 2,
    open: [],
    rec: 50,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["STRATEGY", 16],
    ],
    desc: "After moving, $ can fire immediately where possible",
    desc2: '"Frankly... It would be sheer folly to delay"',
    eid: null,
    id: ["FULL_METAL_BALACLAVA__", 118],
    min: 0,
    name: "Rush",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["UNKNOWN4", 13],
    ],
    desc: "+50% improved aim with firearms",
    desc2:
      '"10$ says I take out his right rear molar at 500m. In any case, I reckon its got a cavity."',
    eid: null,
    id: ["DEATH_GRIP__", 119],
    min: 0,
    name: "Eye of the Tiger",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["CHARACTER", 14],
    ],
    desc: "$ always does maximum damage to any enemy he's already hit",
    desc2: "\"You're going on the list. I'm taking names! \"",
    eid: null,
    id: ["FALL_GUY__", 120],
    min: 0,
    name: "Unforgiving",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["FITNESS", 12],
    ],
    desc: "+100% speed bonus",
    desc2: '"Faster pussycat, Kill, KILL KILLLLLLL."',
    eid: null,
    id: ["STURDY", 121],
    min: 0,
    name: "Sprinter",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 30,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["EQUIPMENT", 11],
    ],
    desc: "Headshots no longer inflict double damage. +1 armor bonus and halves the chance of taking a fatal shot to the head",
    desc2: '"When I was young I hated these things... Now I really like them."',
    eid: 30,
    id: ["FACEBOOT__", 122],
    min: 0,
    name: "Full Metal Balaclava",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["DEFENSE", 10],
    ],
    desc: "$ never drops his weapon even when injured. Even after several hits, $ doesn't lose his target. +1 damage with his fists",
    desc2: '"Haha! Finally my arthritis comes in handy."',
    eid: null,
    id: ["SURVIVOR", 123],
    min: 2,
    name: "Death Grip",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["FITNESS", 12],
    ],
    desc: "If a vehicle belonging to $ is destroyed, damage sustained is divided by 2.",
    desc2:
      '"So, run that by me again – my stunt double was SHOT AND KILLED? I\'m out."',
    eid: null,
    id: ["SURVIVOR_INSTINCT", 124],
    min: 0,
    name: "Fall Guy",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 40,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["PROG", 23],
      ["FITNESS", 12],
    ],
    desc: "+3 life points. $ incurs no penalty when moving with heavy weapons",
    desc2: '"I started lifting weights when I was three don\'t you know."',
    eid: null,
    id: ["TALKY_WALKY", 125],
    min: 0,
    name: "Sturdy",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["FITNESS", 12],
    ],
    desc: "When engaging an enemy in hand-to-hand combat, $ will kick his opponent in the face!",
    desc2: '"Winner of the regimental Golden Boot."',
    eid: null,
    id: ["THOMPSON", 22],
    min: 0,
    name: "Faceboot",
    num: 2,
    open: [],
    rec: 50,
    swe: 3,
    type: ["SUPER", 4],
    vh: null,
    weight: 30,
  },
  {
    cat: [["DEFENSE", 10]],
    desc: "When reinforcements arrive, $ gets back up with one life point",
    desc2: '"Hi guys! About bloody time you showed up!"',
    eid: null,
    id: ["TRAMPLE", 126],
    min: 5,
    name: "Survivor",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "+50% speed bonus when $ drops below half of his life points",
    desc2:
      "\"I don't know about you, but I don't plan on spending eternity here!\"",
    eid: null,
    id: ["TRIGGER_HAPPY", 127],
    min: 0,
    name: "Survival Instinct",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["EQUIPMENT", 11],
      ["DEPLOY", 8],
    ],
    desc: "$ calls a teammate for backup immediately",
    desc2: '"Guess where I\'m calling you from?! "',
    eid: 27,
    id: ["TUCK_AND_ROLL__", 128],
    min: 5,
    name: "Talky-walky",
    num: 1,
    open: [],
    rec: 10,
    swe: 3,
    type: ["SUPER", 4],
    vh: true,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "$ tramples his enemies twice as quickly",
    desc2: '"I have a doormat in my tent for training purposes."',
    eid: null,
    id: ["TWINOID", 129],
    min: 5,
    name: "Stamp",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["UNKNOWN4", 13],
    ],
    desc: "+1 extra shot per burst from any weapon",
    desc2: '"Ooh, this thing\'s pretty sensitive."',
    eid: null,
    id: ["UMP", 23],
    min: 0,
    name: "Trigger Happy",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["DEFENSE", 10],
      ["FITNESS", 12],
    ],
    desc: "$ will roll on the ground to avoid getting hit",
    desc2: '"The key is to avoid puddles and mud. Oh yeah, and mines."',
    eid: null,
    id: ["UNSHAKABLE", 130],
    min: 0,
    name: "Tuck 'n' Roll",
    num: 2,
    open: [],
    rec: 30,
    swe: 5,
    type: ["AUTO", 3],
    vh: null,
    weight: 40,
  },
  {
    cat: [
      ["EQUIPMENT", 11],
      ["SPEED", 7],
    ],
    desc: "$ gains +500 initiative points but becomes poisoned in doing so.",
    desc2: '"No pain, no gain."',
    eid: 21,
    id: ["VENDETTA", 131],
    min: 0,
    name: "Twinoid",
    num: 1,
    open: [],
    rec: 0,
    swe: 3,
    type: ["SUPER", 4],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["FITNESS", 12],
    ],
    desc: "When $ gets hit, it doesn't affect his performance",
    desc2: '"I\'ll complain when the battle is over. Not before."',
    eid: null,
    id: ["VH_HEAVY_TANK", 42],
    min: 0,
    name: "Unshakable",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "When a teammate dies, $ gains 50 initiative points",
    desc2:
      '"Oh no, they got Jimmy! My best friend!<br/>- What? I thought I was your best friend!<br/>- Erm yeah, you are now!"',
    eid: null,
    id: ["VH_HELICOPTER", 41],
    min: 2,
    name: "Vendetta",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["UNKNOWN3", 6],
      ["CHARACTER", 14],
    ],
    desc: "$ aims for parts of the opponent's body which have already been injured",
    desc2:
      '"It\'s nothing personal, but once I start a job I need to finish it."',
    eid: null,
    id: ["VH_LIGHT_TANK", 38],
    min: 0,
    name: "Vicious",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["EQUIPMENT", 11],
      ["SAP", 9],
    ],
    desc: 'All enemies become "cursed"',
    desc2: '"I promise it works chief! My mom taught me how to do it! "',
    eid: 31,
    id: ["VH_MOTO", 39],
    min: 4,
    name: "Voodoo Doll",
    num: 1,
    open: [],
    rec: 70,
    swe: 3,
    type: ["SUPER", 4],
    vh: null,
    weight: 3,
  },
  {
    cat: [
      ["MUNITION", 20],
      ["DEPLOY", 8],
      ["CHARACTER", 14],
    ],
    desc: "All weapons belonging to $ are fully charged before battle",
    desc2:
      '"Always remember two things before battle: put on clean underpants and try not to get shot in the face! "',
    eid: null,
    id: ["VH_FIGHTER_JET__", 40],
    min: 0,
    name: "Battle-ready",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [["DEFENSE", 10]],
    desc: "Reinforcements are called even if you're still alive",
    desc2: '"Call the reinforcements! \nI.. I\'ve bumped my little toe!"',
    eid: null,
    id: ["VICIOUS", 132],
    min: 5,
    name: "Crybaby",
    num: 1,
    open: [],
    rec: 0,
    swe: 1,
    type: ["AUTO", 3],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["OFFENSE", 5],
      ["FITNESS", 12],
    ],
    desc: "$ throws his adversary in hand-to-hand combat",
    desc2:
      "\"Professional disfigurer, at your service! I'm a masked wrestler when I'm not out here trooping.\"",
    eid: null,
    id: ["VOODOO_DOLL__", 133],
    min: 0,
    name: "Wrestler",
    num: 3,
    open: [],
    rec: 20,
    swe: 2,
    type: ["SUPER", 4],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SPEED", 7],
      ["FITNESS", 12],
    ],
    desc: "When $ moves around, he will dodge half the shots fired at him",
    desc2: "\"It's the long way around, but I'll get there.\"",
    eid: null,
    id: ["BATTLE_READY__", 134],
    min: 0,
    name: "Zigzag",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 20,
  },
  {
    cat: [
      ["SPEED", 7],
      ["CHARACTER", 14],
    ],
    desc: "+25% speed bonus as long as $ isn't wounded",
    desc2:
      '"Another glorious day in the Corps! A day in the MT Corps is like a day on the farm. Every meal\'s a banquet! Every paycheck a fortune! Every formation a parade! I LOVE the Corps! \n"',
    eid: null,
    id: ["CRYBABY__", 135],
    min: 0,
    name: "Enthusiastic",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 10,
  },
  {
    cat: [
      ["SUPPORT", 19],
      ["CHARACTER", 14],
      ["DEPLOY", 8],
    ],
    desc: "When $ dies, up to 5 reinforcements join the fight and gain 150 initiative points (once per combat)",
    desc2: '"Vasquez is down! Revenge! "',
    eid: null,
    id: ["WRESTLING", 136],
    min: 10,
    name: "Martyr",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 2,
  },
  {
    cat: [],
    desc: "ne décolle pas sur FLY_TO ou KNOCKOUT",
    desc2: null,
    eid: null,
    id: ["ZIGZAG__", 137],
    min: 0,
    name: "Semelles de plomb",
    num: null,
    open: [],
    rec: null,
    swe: null,
    type: ["PASSIVE", 0],
    vh: null,
    weight: 0,
  },
];

export const RatSkills = [
  112, 55, 70, 76, 79, 97, 74, 53, 114, 117, 123, 116, 131, 137,
];

export type SkillContent = (typeof Skills)[number];

export const BasicWeapons = [8, 13, 18, 32]; // Skill IDs for basic weapons
